@ExampleDDD.Api_HostAddress = https://localhost:44304
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZTk3MzQ3ZS04MzA1LTRhZDItYjVjMi1jYTRiMTZkN2E5YTUiLCJqdGkiOiI1ZDBhZGU5MS0xMTdiLTRkYmYtODIxMC1hOGViZmI0NzIwOTkiLCJnaXZlbl9uYW1lIjoiVGVzdE5hbWUiLCJmYW1pbHlfbmFtZSI6IlRlc3RMYXN0TmFtZSIsImV4cCI6MTcwNDIzNTg3MiwiaXNzIjoiRXhhbXBsZURERCIsImF1ZCI6IkV4YW1wbGVEREQifQ.1rKlhpV6akkqVxpFwov-msKqcTjPoNOtAqU4ldr21d0
@hostId=asdf

POST {{ExampleDDD.Api_HostAddress}}/hosts/{{hostId}}/menus
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Yuumy Menu",
    "description": "A menu description",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "pickles pickles"
                }
            ]
        }
    ]
}