@ExampleDDD.Api_HostAddress = https://localhost:44304
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhMzY0ZDZiNi0zOTgzLTRkZjItOTgxNS01M2YzZjFiNzA0M2IiLCJqdGkiOiJiMDU4YWViNi01MWFmLTRhMWUtOTAxYi0zOWNhZmMwOTc2MDciLCJnaXZlbl9uYW1lIjoiVGVzdE5hbWUiLCJmYW1pbHlfbmFtZSI6IlRlc3RMYXN0TmFtZSIsImV4cCI6MTcwNTczMDgwNCwiaXNzIjoiRXhhbXBsZURERCIsImF1ZCI6IkV4YW1wbGVEREQifQ.nS1xxCn8yTgtmOVDkKOcwo5wbmC_TBU6WXgRyxB9rjk
@hostId=0f8fad5b-d9cb-469f-a165-70867728950e

POST {{ExampleDDD.Api_HostAddress}}/hosts/{{hostId}}/menus
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "name": "Yuumy Menu",
    "description": "A menu description",
    "sections": [
        {
            "name": "Appetizers",
            "description": "Starters",
            "items": [
                {
                    "name": "Fried Pickles",
                    "description": "pickles pickles"
                }
            ]
        }
    ]
}